### ISSUE TITLE
Final Submission Checklist

### ISSUE THREAD

**Issue by carlow78** [carlow78/brew-bliss#24]
* [x] secret_key updated and not saved to github
* [x] debug is set to false
* [x] project is set to public
* [x] issues/user stories is set public
* [x] all links work as expected
